ezcoins:
  name: taskezcoins项目
  profile: E:/taskezcoins/uploadPath
  addressEnabled: false
  captchaType: math
  emailLog: emailLogo.png

wallet:
   cc:
    #公钥
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA07L/9eSyDhmPpUg2jBw1SmgNaGHnWglzj25rgLI4vsmoULjLYk81QBrvP1STDnrgRgR0wK8AmfnzA7BU2+73jduU0xpkZzlY05sjL4dFBX0UIvNoCKFP0DE+weG4Aqk1wFV2/vx1Q8yctb/kWxNS/NUKi+Ab9hpSEm8x9CQ2Q+VgLc9cWRQ9bQliGp4db9O8pfPdTHHi+UgYXavPtOrADREzunbaRdClyTb9774v0kYuKOFEsvYHbOpFa2L+WoyJ+I1yTEJ+1FyIJu1tcsaaW7AIo8N1h2CybYr7RRJwV9BAjFexXyr6b+0sBiM2ZTcXC4L5qya3JW2iN5R0l5GO8QIDAQAB
    #第三方网关
    gateway: https://wallet.ezcoins.cc

# 优盾支付配置
#线上环境 02763
bipay:
  #商户号
  merchantId: 3
  #key为接口授权码APIKEY，由网关分配给商户
  merchantKey: 47023067b4ac0b6d3cab1f667acc81c7
  #优盾钱包网关香港
  gateway: https://hk06-hk-node.uduncloud.com
  #结果回调地址
  host: http://Hotelmillionaire.com
  supported-coins: BTC,ETH,TRX

huobi:
  restapi:
    gateway: https://api.huobi.pro/v1/common/currencys

logging:
  level:
    ROOT: DEBUG
    com.ezcoins: warn
    org.springframework: DEBUG
    io.lettuce.core.protocol: warn

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 9
    password: 123456
    timeout: 15s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 11
        max-wait: -1ms
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uri : mongodb://test:123456@localhost:27017/db_ezcoins

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      master:
        url: jdbc:mysql://127.0.0.1:3306/db_ezcoins?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
        username: root
        password: root
      initialSize: 5
      minIdle: 10
      maxActive: 30
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 900000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        allow:
        url-pattern: /druid/*
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

    jpa:
      # CREATE DATABASE `aipay` DEFAULT CHARACTER SET = utf8;
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      database: MYSQL
      show-sql: true
      properties:
        hibernate.id.new_generator_mappings: true
        hibernate.connection.provider_disables_autocommit: true
        hibernate.cache.use_second_level_cache: false
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: true
      hibernate:
        ddl-auto: update

  mail:
    #服务器
    host: smtpout.secureserver.net
      #邮箱发件人
    username: support@ezcoins.cc
      #授权码
    password: P@ssw0rdEzcoins
    properties:
      mail:
        debug: true
        smtp:
          ssl:
            enable: false
          socketFactory:
            port: 587
            class: javax.net.ssl.SSLSocketFactory
          # 必须进行授权认证，它的目的就是阻止他人任意乱发邮件
    protocol: smtp
    default-encoding: utf-8
    port: 587
#          auth: true
#          starttls:
#            enable: true
#            required: true
token:
    header: Authorization
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）（7天=10080分钟）
    expireTime: 10080
  
mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: reuse
    #log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    #开启SQL语句打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #自动驼峰命名
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  # 配置mybatis 数据返回类型别名（默认别名为类名）
  type-aliases-package: com.ezcoins.project.**.domain

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

aliyun:
  oss:
    file:
      endpoint: oss-cn-hongkong.aliyuncs.com
      keysecret: TPsafSxWx3cL7RcysEjNv2PmnWFVLQ
      keyid: LTAI5tLymnkxKkzbnu6Jpdmh
      bucketname: hotel-app-static


management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          ['configprops', 'env', 'health', 'info', 'jhimetrics', 'logfile', 'loggers', 'prometheus', 'threaddump', 'caches', 'liquibase']
  endpoint:
    health:
      show-details: when_authorized
      roles: 'ROLE_ADMIN'
      probes:
        enabled: true
    jhimetrics:
      enabled: true
  info:
    git:
      mode: full
  health:
    group:
      liveness:
        include: livenessState
      readiness:
        include: readinessState,db
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true
  metrics:
    export:
      # Prometheus is the default metrics backend
      prometheus:
        enabled: true
        step: 60
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    tags:
      application: ${spring.application.name}
    web:
      server:
        request:
          autotime:
            enabled: true
