ezcoins:
  name: taskezcoins项目
  profile: /data/ezcoins/uploadPath
  addressEnabled: false
  captchaType: math
  emailLog: emailLogo.png

# 优盾支付配置
#线上环境 02763
bipay:
  #商户号
  merchantId: 3
  #key为接口授权码APIKEY，由网关分配给商户
  merchantKey: 47023067b4ac0b6d3cab1f667acc81c7
  #优盾钱包网关香港
  gateway: https://hk06-hk-node.uduncloud.com
  #结果回调地址
  host: http://Hotelmillionaire.com
  supported-coins: BTC,ETH,TRX

wallet:
  cc:
    #公钥
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA07L/9eSyDhmPpUg2jBw1SmgNaGHnWglzj25rgLI4vsmoULjLYk81QBrvP1STDnrgRgR0wK8AmfnzA7BU2+73jduU0xpkZzlY05sjL4dFBX0UIvNoCKFP0DE+weG4Aqk1wFV2/vx1Q8yctb/kWxNS/NUKi+Ab9hpSEm8x9CQ2Q+VgLc9cWRQ9bQliGp4db9O8pfPdTHHi+UgYXavPtOrADREzunbaRdClyTb9774v0kYuKOFEsvYHbOpFa2L+WoyJ+I1yTEJ+1FyIJu1tcsaaW7AIo8N1h2CybYr7RRJwV9BAjFexXyr6b+0sBiM2ZTcXC4L5qya3JW2iN5R0l5GO8QIDAQAB
    #第三方网关
    gateway: https://wallet.ezcoins.cc


logging:
  level:
    com.ezcoins: debug
    org.springframework: warn
    io.lettuce.core.protocol: error

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 9
    password: "@#!666666pk.123^%!*"
    timeout: 15s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 11
        max-wait: -1ms
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: kckjQHrjnZsSYF6
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      master:
        url: jdbc:mysql://127.0.0.1:3306/db_ezcoins?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai
        username: dbadmin
        password: viZ%2EMEe@7eoMG6%5=28
      initialSize: 5
      minIdle: 10
      maxActive: 30
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 900000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        allow:
        url-pattern: /druid/*
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  mail:
    #服务器
    host: smtpout.secureserver.net
    #邮箱发件人
    username: support@ezcoins.cc
    #授权码
    password: P@ssw0rdEzcoins
    properties:
      mail:
        smtp:
          ssl:
            enable: false
          socketFactory:
            port: 587
            class: javax.net.ssl.SSLSocketFactory
          # 必须进行授权认证，它的目的就是阻止他人任意乱发邮件
    protocol: smtp
    default-encoding: utf-8
    port: 587


token:
  header: Authorization
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）（7天=10080分钟）
  expireTime: 10080

mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: reuse
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  type-aliases-package: com.ezcoins.project.**.domain

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

aliyun:
  oss:
    file:
      endpoint: oss-cn-hongkong.aliyuncs.com
      keysecret: TPsafSxWx3cL7RcysEjNv2PmnWFVLQ
      keyid: LTAI5tLymnkxKkzbnu6Jpdmh
      bucketname: hotel-app-static

